name: CI workflow

on: [push, pull]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      use: |
        python -m unittest discover